services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:Noirlabrules!@db:5432/db
    networks:
      - mynetwork
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Noirlabrules!
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - mynetwork


networks:
    mynetwork:
      driver: bridge

volumes:
  postgres_data:
