services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://noirlab_user:admin@db:5432/noirlab_db
    networks:
      - mynetwork
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=noirlab_user
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=noirlab_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U noirlab_user -d noirlab_db"]
      interval: 5s
      retries: 5
      start_period: 10s
    networks:
      - mynetwork


networks:
    mynetwork:
      driver: bridge

volumes:
  postgres_data:
